"""
Online preference optimization with TRL + DeepSpeed: Online DPO, Nash-MD, XPO.

THE GAP THIS FILLS
------------------
`03_huggingface/05_dpo` learns from a FIXED dataset collected before training
started. `03_huggingface/06_grpo` samples fresh rollouts and scores them with a
VERIFIER.

Between those sits the case a lot of real alignment work lands in: you want
fresh on-policy samples, but you have no verifier -- only a judge that can say
which of two responses is better.

WHY OFFLINE DPO PLATEAUS
------------------------
Your preference pairs were generated by SOME model -- an earlier checkpoint, a
different model, a human. As training proceeds the policy moves away from
whatever produced that data, and within a few hundred steps it is generating
responses unlike anything in the dataset. You now have **no preference signal
for the region the policy actually occupies**.

The symptom is specific and easy to misread: DPO improves, then plateaus or
degrades, while `rewards/margins` keeps climbing. The margin is measuring
separation on stale data, so it looks healthy while the model does not improve.

Online methods regenerate the pairs every step, so the data follows the policy.

THE THREE METHODS
-----------------
    online_dpo   The smallest change to DPO: sample two responses from the
                 CURRENT policy, ask a judge which is better, apply the DPO
                 loss. Everything else is unchanged.

    nash_md      Keeps the PREFERENCE MODEL instead of collapsing it to a
                 scalar reward, and seeks the Nash equilibrium of the resulting
                 game. Robust to intransitive preferences (A beats B beats C
                 beats A), which a single scalar reward cannot represent.

    xpo          Online DPO plus a principled exploration bonus. Online
                 sampling can only ever learn about responses the policy is
                 already somewhat likely to produce; if a better mode sits at
                 near-zero probability, sampling will never find it. XPO
                 deliberately pushes toward under-sampled regions.

WHAT PLAYS THE JUDGE
--------------------
    a reward model   cheap; needs ../04_reward_model first
    a stronger LLM   this is RLAIF; moderate cost
    a human          rarely feasible online
    a rule/verifier  ~free -- but then use GRPO, which is built for it

ONLINE IS NOT CHEAP
-------------------
You now pay for generation every step (two samples per prompt) plus judging.
That is most of GRPO's cost profile without GRPO's group baseline. Reach for
this when offline DPO has VISIBLY plateaued, not by default.

Dataset shape changes too: offline DPO needs prompt/chosen/rejected; online
needs only PROMPTS. The pairs are manufactured during training.

RUNNING IT
----------
CoreWeave / SLURM:      sbatch run_deepspeed.sh
RunPod (auto-shutdown): uv run runpod/runpod_ctl.py run 03_huggingface/07_online_dpo \
                            --dry-run --collect --wait --terminate --yes

    uv venv && source .venv/bin/activate
    uv pip install torch --index-url https://download.pytorch.org/whl/cu128
    uv pip install deepspeed transformers trl peft accelerate datasets

References:
- Guo et al. "Direct Language Model Alignment from Online AI Feedback."
  https://arxiv.org/abs/2402.04792
- Munos et al. "Nash Learning from Human Feedback."
  https://arxiv.org/abs/2312.00886
- Xie et al. "Exploratory Preference Optimization." https://arxiv.org/abs/2405.21046
"""

import argparse
import os
import sys

try:
    import wandb  # noqa: F401
    WANDB_AVAILABLE = True
except ImportError:
    WANDB_AVAILABLE = False


METHODS = {
    "online_dpo": "Sample two, judge, apply the DPO loss. Start here.",
    "nash_md":    "Nash equilibrium of the preference model; handles intransitivity.",
    "xpo":        "Online DPO + exploration bonus; strongest guarantees.",
}


def require_gpu() -> None:
    """
    Stop with a clear message when no CUDA device is available.

    Without this, DeepSpeed gets as far as building its fused Adam kernel and
    dies with `OSError: CUDA_HOME environment variable is not set` raised from
    deep inside torch's C++ extension loader -- which tells a newcomer nothing
    about what went wrong or what to do next.

    Set ALLOW_CPU=1 to bypass.
    """
    import os   # noqa: F811
    import sys  # noqa: F811

    try:
        import torch
    except ImportError:
        print("\n[preflight] PyTorch is not installed. Install it with:")
        print("            uv pip install torch --index-url "
              "https://download.pytorch.org/whl/cu128\n")
        sys.exit(1)

    if torch.cuda.is_available():
        return

    if os.environ.get("ALLOW_CPU") == "1":
        print("\n[preflight] No GPU detected; ALLOW_CPU=1 set, continuing.")
        print("            ds_config.json also needs \"torch_adam\": true and "
              "bf16 disabled,")
        print("            or DeepSpeed will still fail building its CUDA ops.\n")
        return

    bar = "=" * 72
    print("\n" + bar)
    print("  NO GPU DETECTED - stopping before DeepSpeed fails obscurely")
    print(bar)
    print("\n  torch.cuda.is_available() returned False.")
    print("\n  Online preference optimization GENERATES during training and")
    print("  holds a policy, a reference AND a judge. Budget like GRPO —")
    print("  roughly 24 GB for a 0.6B policy with a small judge.")
    print("\n  Start with the OFFLINE objectives instead; they run on CPU:")
    print("      uv run 03_huggingface/05_dpo/preference_losses.py")
    print("      uv run tests/test_preference_losses.py  # 58 checks, no GPU")
    print("\n  Check your setup:")
    print("      nvidia-smi")
    print("      ds_report")
    print("\n  Rent a GPU (needs RUNPOD_API_KEY):")
    print("      uv run runpod/runpod_ctl.py recommend 03_huggingface/07_online_dpo")
    print("      uv run runpod/runpod_ctl.py run 03_huggingface/07_online_dpo \\")
    print("          --dry-run --collect --wait --terminate --yes")
    print("\n" + bar + "\n")
    sys.exit(1)


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--method", default="online_dpo", choices=sorted(METHODS))
    parser.add_argument("--list-methods", action="store_true",
                        help="Print the method table and exit. Needs no GPU.")
    parser.add_argument("--model", default="Qwen/Qwen3-0.6B")
    parser.add_argument("--reward-model", default=None,
                        help="Path to a trained reward model to act as judge. "
                             "Build one with ../04_reward_model/. "
                             "Mutually exclusive with --judge.")
    parser.add_argument("--judge", default=None,
                        help="TRL judge name (e.g. an LLM-as-judge). "
                             "Mutually exclusive with --reward-model.")
    parser.add_argument("--dataset", default="trl-lib/ultrafeedback-prompt",
                        help="PROMPT-ONLY dataset. Online methods manufacture "
                             "the pairs themselves.")
    parser.add_argument("--beta", type=float, default=0.1)
    parser.add_argument("--lora-rank", type=int, default=16)
    parser.add_argument("--no-lora", action="store_true")
    parser.add_argument("--epochs", type=float, default=1.0)
    parser.add_argument("--warmup-steps", type=int, default=10,
                        help="LR warmup steps. Must be >0: ds_config.json "
                             "leaves warmup_num_steps 'auto', HuggingFace "
                             "fills it from this, and DeepSpeed rejects 0 "
                             "with 'warmup_num_steps must be a positive "
                             "integer'. Clamped for short runs.")
    parser.add_argument("--max-samples", type=int, default=-1,
                        help="Use only the first N prompts. Online methods generate\n"
                             "fresh completions every step, so the prompt set is\n"
                             "cheap to shrink and the generation is what costs.")
    parser.add_argument("--max-steps", type=int, default=-1,
                        help="Cap steps; the RunPod --dry-run path uses this.")
    parser.add_argument("--batch-size", type=int, default=2)
    parser.add_argument("--grad-accum", type=int, default=8)
    parser.add_argument("--learning-rate", type=float, default=5e-7)
    parser.add_argument("--max-new-tokens", type=int, default=64,
                        help="Generation length per sample. This is the main "
                             "cost knob — you generate TWO of these per prompt "
                             "every step.")
    parser.add_argument("--output", default=None)
    parser.add_argument("--deepspeed", default="ds_config.json")
    # parse_known_args, NOT parse_args: the DeepSpeed launcher injects
    # --local_rank=N into every worker's argv, and a strict parser exits 2
    # with "unrecognized arguments" before training starts -- breaking the
    # exact command this example documents. CONTRIBUTING.md section 3.2.
    args = parser.parse_known_args()[0]
    # DeepSpeed's WarmupDecayLR rejects warmup_num_steps=0. ds_config.json
    # leaves it "auto"; HuggingFace substitutes TrainingArguments.warmup_steps,
    # which defaults to 0 -- so without setting it, EVERY DeepSpeed run of this
    # example dies before step one with
    #   ValueError: warmup_num_steps must be a positive integer, got 0
    # Clamped so a short --max-steps smoke test does not request more warmup
    # than it has steps to give.
    warmup_steps = args.warmup_steps
    if args.max_steps > 0:
        warmup_steps = max(1, min(warmup_steps, max(1, args.max_steps // 2)))
    if args.list_methods:
        bar = "=" * 76
        print(bar)
        print("  Online preference optimization")
        print(bar)
        for name, note in METHODS.items():
            print(f"  {name:<12} {note}")
        print(bar)
        print("  All three need a JUDGE: --reward-model or --judge.")
        print("  If you have a ground-truth verifier instead, use")
        print("  ../06_grpo/ — a verifier beats any judge.")
        return

    # Catch the misconfiguration that otherwise fails deep inside the trainer.
    if bool(args.reward_model) == bool(args.judge):
        raise SystemExit(
            "Online methods need exactly one preference source: pass either "
            "--reward-model or --judge, not both and not neither. Without one "
            "there is nothing to rank the sampled pairs, which is the entire "
            "point of going online. Build a reward model with "
            "../04_reward_model/."
        )

    output = args.output or f"./{args.method}-{args.model.split('/')[-1]}"
    require_gpu()

    import torch
    from datasets import load_dataset
    from peft import LoraConfig

    bar = "=" * 76
    print(bar)
    print(f"  {args.method} — online preference optimization")
    print(bar)
    print(f"  model            {args.model}")
    print(f"  device           {torch.cuda.get_device_name(0)}")
    print(f"  judge            {args.reward_model or args.judge}")
    print(f"  dataset          {args.dataset}  (prompts only)")
    print(f"  max_new_tokens   {args.max_new_tokens}  "
          f"(x2 samples x every step — the cost driver)")
    print(bar)

    dataset = load_dataset(args.dataset, split="train")
    if args.max_samples > 0:
        n = min(args.max_samples, len(dataset))
        dataset = dataset.select(range(n))
        print(f"  --max-samples: using {n} of the split's prompts")

    # A prompt-only dataset is required. Handing this an offline preference set
    # wastes the chosen/rejected columns silently, so say so.
    if "chosen" in dataset.column_names:
        print("  [note] dataset has chosen/rejected columns; online methods")
        print("         IGNORE them and generate fresh pairs. If you meant to")
        print("         use them, ../05_dpo/ is far cheaper.")

    peft_config = None if args.no_lora else LoraConfig(
        r=args.lora_rank, lora_alpha=args.lora_rank * 2, lora_dropout=0.05,
        bias="none", task_type="CAUSAL_LM",
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    )

    # The preference source is built AFTER the trainer class is resolved
    # (below), because which argument it goes into depends on the TRL version.
    # Building it here would mean loading a reward model we might then have to
    # hand over as a path string instead.

    common = dict(
        output_dir=output,
        num_train_epochs=args.epochs,
        max_steps=args.max_steps,
        warmup_steps=warmup_steps,
        per_device_train_batch_size=args.batch_size,
        gradient_accumulation_steps=args.grad_accum,
        learning_rate=args.learning_rate,
        max_new_tokens=args.max_new_tokens,
        beta=args.beta,
        gradient_checkpointing=True,
        bf16=True,
        logging_steps=10,
        save_strategy="epoch",
        deepspeed=args.deepspeed if os.path.exists(args.deepspeed) else None,
        report_to="wandb" if (WANDB_AVAILABLE and os.environ.get("WANDB_API_KEY"))
                  else "none",
    )

    # WHERE these live depends on the TRL version, and it moved.
    #
    # Up to TRL 0.x all three were top-level (`from trl import OnlineDPOConfig`).
    # As of TRL 1.12 the online trainers sit under trl.experimental.<method>,
    # alongside CPOTrainer and BCOTrainer which moved earlier. A hardcoded
    # top-level import raises
    #     ImportError: cannot import name 'OnlineDPOConfig' from 'trl'
    # on any current install -- which is what every 2-GPU run of this example
    # did, for all three methods.
    #
    # Try the stable location first, then the experimental one, so this works
    # across both. The warning TRL prints on experimental imports is expected
    # and is silenced here rather than alarming the reader.
    import os as _os
    _os.environ.setdefault("TRL_EXPERIMENTAL_SILENCE", "1")

    _WANTED = {
        "online_dpo": ("OnlineDPOConfig", "OnlineDPOTrainer"),
        "nash_md":    ("NashMDConfig", "NashMDTrainer"),
        "xpo":        ("XPOConfig", "XPOTrainer"),
    }
    cfg_name, trainer_name = _WANTED[args.method]

    def _resolve(name: str):
        import importlib
        import trl
        if hasattr(trl, name):
            return getattr(trl, name)
        try:
            mod = importlib.import_module(f"trl.experimental.{args.method}")
        except ImportError as exc:
            raise SystemExit(
                f"{name} is not available in trl {getattr(trl, '__version__', '?')}: "
                f"{exc}\n  It is neither top-level nor in "
                f"trl.experimental.{args.method}. Online methods are a moving "
                f"target in TRL; pin a version or use ../05_dpo/, "
                f"whose objectives are stable."
            ) from exc
        if not hasattr(mod, name):
            raise SystemExit(
                f"{name} not found in trl.experimental.{args.method} "
                f"(trl {getattr(trl, '__version__', '?')})."
            )
        return getattr(mod, name)

    Cfg, Trainer_ = _resolve(cfg_name), _resolve(trainer_name)

    # nash_md is broken upstream in TRL 1.12, and the symptom is unhelpful.
    #
    # GeometricMixtureWrapper.forward -- which produces the logits the LOSS is
    # computed from -- is decorated @torch.inference_mode(). Tensors created
    # under inference mode cannot be saved for backward, so the first optimizer
    # step dies with
    #     RuntimeError: Inference tensors cannot be saved for backward.
    # inside a LayerNorm, naming neither nash_md nor TRL.
    #
    # online_dpo and xpo are unaffected: they use inference_mode only around
    # REWARD computation, whose outputs never need gradients. So this is
    # specific to nash_md, not to this example.
    #
    # Detected by inspecting the decorator rather than matching a version
    # string, so it stops firing by itself once TRL fixes it.
    if args.method == "nash_md":
        import inspect as _i
        try:
            from trl.experimental.nash_md import nash_md_trainer as _nm
            _wrapper_src = _i.getsource(_nm.GeometricMixtureWrapper.forward)
        except Exception:
            _wrapper_src = ""
        if "inference_mode" in _wrapper_src:
            import trl as _t
            raise SystemExit(
                "nash_md cannot train on trl "
                f"{getattr(_t, '__version__', '?')}: its GeometricMixtureWrapper"
                ".forward is decorated @torch.inference_mode(), and the logits "
                "it returns feed the loss. The first backward pass fails with "
                "'Inference tensors cannot be saved for backward'.\n"
                "  This is an upstream TRL bug, not a problem with your setup "
                "or this repository.\n"
                "  Use --method online_dpo or --method xpo, which take the same "
                "arguments and are unaffected."
            )
    print(f"  trainer          {Trainer_.__module__}.{Trainer_.__name__}")

    # WHICH ARGUMENT the preference source goes into also changed.
    #
    # Older TRL: OnlineDPOTrainer(reward_model=..., judge=...) -- two separate
    # parameters, and a set of *Judge classes to choose from.
    # TRL 1.12:  OnlineDPOTrainer(reward_funcs=...) -- one parameter taking a
    # model path, a PreTrainedModel or a callable, and NO judge classes at all;
    # they were removed, not moved.
    #
    # Passing the old keyword to the new trainer raises
    #   TypeError: OnlineDPOTrainer.__init__() got an unexpected keyword
    #   argument 'reward_model'
    # so this inspects the signature rather than assuming either shape.
    import inspect as _inspect
    _params = _inspect.signature(Trainer_.__init__).parameters
    _modern = "reward_funcs" in _params

    reward_model = judge = None
    if args.judge:
        import trl as _trl
        judge_cls = getattr(_trl, args.judge, None)
        if judge_cls is None:
            available = sorted(n for n in dir(_trl) if n.endswith("Judge"))
            raise SystemExit(
                f"Unknown judge {args.judge!r}. "
                + (f"This TRL exposes: {', '.join(available)}."
                   if available else
                   f"trl {getattr(_trl, '__version__', '?')} ships NO judge "
                   "classes at all -- they were removed, not relocated. Use "
                   "--reward-model instead: pass any sequence-classification "
                   "model, e.g. one built by "
                   "../04_reward_model/.")
            )
        try:
            judge = judge_cls()
        except ImportError as exc:
            raise SystemExit(
                f"{args.judge} could not be constructed: {exc}\n"
                "  Most TRL judges pull an extra dependency or an API key. "
                "Install it, or use --reward-model instead."
            )

    if _modern:
        # Pass LOADED models, not path strings.
        #
        # Given a string, TRL calls AutoModel*.from_pretrained itself, and
        # transformers attaches a device_map -- which ZeRO-3 refuses:
        #     ValueError: DeepSpeed Zero-3 is not compatible with passing a
        #     `device_map`.
        # This example is ZeRO-3 on purpose (it generates during training), so
        # the loading has to happen here, without a device_map, and DeepSpeed
        # places the shards.
        if args.reward_model:
            from transformers import (AutoModelForSequenceClassification,
                                      AutoTokenizer as _AutoTok)
            source = AutoModelForSequenceClassification.from_pretrained(
                args.reward_model, num_labels=1, dtype=torch.bfloat16
            )
            reward_tok = _AutoTok.from_pretrained(args.reward_model)
            if reward_tok.pad_token is None:
                reward_tok.pad_token = reward_tok.eos_token
        else:
            source = judge
            reward_tok = None
        trainer_kwargs = {"reward_funcs": source}
        # Not every trainer takes it: NashMDTrainer has no
        # reward_processing_classes parameter while OnlineDPO and XPO do.
        if reward_tok is not None and "reward_processing_classes" in _params:
            trainer_kwargs["reward_processing_classes"] = reward_tok
    else:
        if args.reward_model:
            from transformers import AutoModelForSequenceClassification
            reward_model = AutoModelForSequenceClassification.from_pretrained(
                args.reward_model, num_labels=1, dtype=torch.bfloat16
            )
        trainer_kwargs = {"reward_model": reward_model, "judge": judge}
    print(f"  preference arg   {', '.join(trainer_kwargs)}")
    print(f"  trainer          {Trainer_.__module__}.{Trainer_.__name__}")

    # TRL 1.12 requires the tokenizer explicitly -- older versions inferred it
    # from the model string. Without it:
    #     ValueError: `processing_class` must be provided.
    # A padding token is mandatory too, because online methods batch generated
    # completions of different lengths every step; Qwen and most causal models
    # ship without one.
    from transformers import AutoTokenizer
    tokenizer = AutoTokenizer.from_pretrained(args.model)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    # Same reason as the reward model: hand the trainer an already-loaded
    # policy so transformers never gets the chance to attach a device_map.
    from transformers import AutoModelForCausalLM
    policy = AutoModelForCausalLM.from_pretrained(args.model, dtype=torch.bfloat16)

    trainer = Trainer_(
        model=policy,
        **trainer_kwargs,
        args=Cfg(**common),
        train_dataset=dataset,
        processing_class=tokenizer,
        peft_config=peft_config,
    )

    trainer.train()
    trainer.save_model(output)

    print(f"\n  saved to {output}")
    print("\n  Next: ../06_grpo/ — if a ground-truth verifier")
    print("  exists for your task, it beats any judge and costs nothing to")
    print("  evaluate.")


if __name__ == "__main__":
    main()
